### ISSUE TITLE
Installed Plugin Using Sketch Toolbox - No Data for Today

### ISSUE THREAD

**Issue by JWhiteUX** [wakatime/sketch-wakatime#1]
I started using this plugin maybe 15 - 20 mins ago and have not been able to test it's connection successfully. Is this normal behavior? I've tried using a different API Key as well.

I've restarted Sketch as well.

Late 2015 Macbook
Latest El Capitan
Latest Sketch
etc etc
<img width="792" alt="screenshot 2016-06-15 17 11 38" src="https://cloud.githubusercontent.com/assets/12961108/16101614/49e46c38-331c-11e6-8491-d7a4042623d7.png">

**Comment by alanhamlett** [comment]
Which version of Sketch are you using?

Can you add this line to `~/.wakatime.cfg`:
`debug = true`

Open the Console app, search for sketch, and restart Sketch app. Then change some selections in a drawing.

**Comment by mathiasm** [comment]
Same thing here. I''ve been testing all day long and there is still no data. Using Sketch 3.8.3 (29802).

**Comment by JWhiteUX** [comment]
Sketch - Version 3.8.3 (29802) 

Will add that debug line

**Comment by JWhiteUX** [comment]
<img width="943" alt="screenshot 2016-06-16 13 18 16" src="https://cloud.githubusercontent.com/assets/12961108/16131776/e086d7d6-33c4-11e6-828c-3d54fa8976cb.png">
Added that line, and restarted sketch. No dice.
<img width="264" alt="screenshot 2016-06-16 13 14 41" src="https://cloud.githubusercontent.com/assets/12961108/16131694/5c6e0c26-33c4-11e6-84f0-1465e7433411.png">

**Comment by alanhamlett** [comment]
When you search for `sketch` in your Console app, do you see any WakaTime related messages?

**Comment by JWhiteUX** [comment]
I need a little more context. When you say "console app" do you mean Terminal? Is there a specific location the debug info is saved to?

Output
`MacBook-Pro:~ justinwhite$ mdfind "sketch"
MacBook-Pro:~ justinwhite$ mdfind "sketch" | grep WakaTime
/Users/justinwhite/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Wakatime/WakaTime.sketchplugin
/Users/justinwhite/Library/Containers/com.bohemiancoding.sketch3/Data/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Wakatime/WakaTime.sketchplugin
MacBook-Pro:~ justinwhite$`

**Comment by alanhamlett** [comment]
The debug logs go to `/var/log/system.log`, but you should use the Console app (available in your Applications folder) to search the logs.

From Spotlight (`CMD` + `Space`) type `console` to find the Console app.

**Comment by JWhiteUX** [comment]
I let it run a while, and it logged a bunch of output.
![screenshot 2016-06-16 16 50 05](https://cloud.githubusercontent.com/assets/12961108/16136782/757d0c12-33e2-11e6-978d-84c06ad979b7.png)

> 6/16/16 4:27:33.301 PM main (Sketch Plugin)[30574]: [WakaTime] [DEBUG] /usr/bin/python /Users/justinwhite/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Wakatime/WakaTime.sketchplugin/Contents/Resources/wakatime/cli.py --file /Users/justinwhite/Dropbox%20(DataScience)/Product%20Team/DS-Apps/Apps-and-Views/App-Data-Explorer/ds-app-aldrin2-wireframes.sketch --plugin sketch/3.8.3 sketch-wakatime/1.0.5
> 
> 6/16/16 4:29:34.383 PM main (Sketch Plugin)[30574]: [WakaTime] [DEBUG] /usr/bin/python /Users/justinwhite/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Wakatime/WakaTime.sketchplugin/Contents/Resources/wakatime/cli.py --file /Users/justinwhite/Dropbox%20(DataScience)/Product%20Team/DS-Apps/Apps-and-Views/App-Data-Explorer/ds-app-aldrin2-wireframes.sketch --plugin sketch/3.8.3 sketch-wakatime/1.0.5
> 
> 6/16/16 4:35:22.138 PM main (Sketch Plugin)[30574]: [WakaTime] [DEBUG] Skipping current drawing because not enough time passed:/Users/justinwhite/Dropbox%20(DataScience)/Product%20Team/DS-Apps/Apps-and-Views/App-Data-Explorer/ds-app-aldrin2-wireframes.sketch

**Comment by alanhamlett** [comment]
The `%20` in the file path was causing the file to not be found by wakatime-cli, so url decoding the file path should have fixed this. Can you download the latest release and reinstall:
https://github.com/wakatime/sketch-wakatime/releases/latest

**Comment by JWhiteUX** [comment]
Looks like the plugin is working! Thank you!
<img width="318" alt="screenshot 2016-06-27 09 41 12" src="https://cloud.githubusercontent.com/assets/12961108/16388114/72bc1866-3c4c-11e6-81b8-5e5e038a2baa.png">
