### ISSUE TITLE
Sketch intgeration not working

### ISSUE THREAD

**Issue by feisty07** [wakatime/sketch-wakatime#10]
Hello.

I am currently running  Sketch Version Version 96.3 (167315) and Sketch Wakatime plugin 3.0.3.
I have tried updating both, and reinstalling a couple of times and nothing seems to work, no logs are showing up on my dashboard. 

Any recommendations?

**Comment by feisty07** [comment]
@alanhamlett can you help?

<img width="1014" alt="Screenshot 2023-05-26 at 11 51 23" src="https://github.com/wakatime/sketch-wakatime/assets/126291565/0ae2267e-8af2-46c5-936e-55d68bff42c1">

<img width="1014" alt="Screenshot 2023-05-26 at 11 51 56" src="https://github.com/wakatime/sketch-wakatime/assets/126291565/ca4b62b1-9e04-43f5-a29a-0a00432a2a34">

**Comment by feisty07** [comment]
HELLO??

**Comment by alanhamlett** [comment]
Fixed in v4.0.0
