### ISSUE TITLE
wakatime not logging Sketch hours

### ISSUE THREAD

**Issue by feisty07** [wakatime/sketch-wakatime#11]
Hello, my Wakatime stopped working on the 20th of June. Yes, it is up to date, yes, I have generated new keys, yes, my sketch is up to date. Please help resolve this, as it affects my work.

<img width="1453" alt="Screenshot 2023-06-26 at 23 45 24" src="https://github.com/wakatime/sketch-wakatime/assets/126291565/d4d1f756-761c-4149-8a13-61836ce4fb8a">

<img width="1453" alt="Screenshot 2023-06-26 at 23 45 05" src="https://github.com/wakatime/sketch-wakatime/assets/126291565/23601565-5a41-4eca-b5b1-d21b9b2206a1">

<img width="974" alt="Screenshot 2023-06-26 at 23 46 39" src="https://github.com/wakatime/sketch-wakatime/assets/126291565/ef81190d-9c67-46da-b6aa-89d76e4cd998">

**Comment by alanhamlett** [comment]
Are you available for a Zoom to debug it real time? What I want to do is:

1. `git clone git@github.com:wakatime/sketch-wakatime.git`
2. `cd sketch-wakatime`
3. `ln -sf WakaTime.sketchplugin ~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/WakaTime.sketchplugin`
4. Uncomment this line:
https://github.com/wakatime/sketch-wakatime/blob/571b40731a5e85dbcf739d4c911aff4dec3792f9/src/sendHeartbeat.js#L14
5. `npm run build`
6. Check your `Console.app` for messages from `process:Sketch` and search term `wakatime`

**Comment by feisty07** [comment]
Hello Alan,

I am available for a call.

**Comment by alanhamlett** [comment]
Do u have a time that works best for you? Or you can choose a time from my calendar: https://calendly.com/alan-hamlett/30min

**Comment by feisty07** [comment]
Hello Alan,

Im available for the call tomorrow. I already scheduled 12 noon on your
calendar.

Thanks for the timely response.

Warm regards
PJ

**Comment by feisty07** [comment]
Hello Alan,

I have yet to receive the zoom link for our meeting at 12 noon (WAT).

Can you share one with me?

Regards,
PJ

**Comment by alanhamlett** [comment]
@feisty07 I've sent the zoom link to your email address. I'll have the Zoom meeting open now, see you there!

**Comment by feisty07** [comment]
Hello,

Got the invite. I'm on and waiting for you.


Precious Juwah

UI/UX Design - Lead


www.initsng.com | +234 802 1344 866


283, Herbert Macaulay Way,

Lagos Mainland, Lagos, Nigeria.

**Comment by alanhamlett** [comment]
I found a bug https://github.com/skpm/child_process/pull/38 that was preventing stderr output from [wakatime-cli](https://github.com/wakatime/wakatime-cli) from being logged to Console.app. Now I've released a new sketch-wakatime version that prints any errors to Console.app.

@feisty07 can you upgrade the sketch-wakatime plugin and then add this line to your `~/.wakatime.cfg` file:

`debug = true`

**Comment by alanhamlett** [comment]
Fixed in v4.0.1.

**Comment by feisty07** [comment]
Great!

Thank you for your timely assistance.

Warm regards,
