### ISSUE TITLE
Sketch and Wakatime - Uninstallation

### ISSUE THREAD

**Issue by JWhiteUX** [wakatime/sketch-wakatime#4]
How do I uninstall Wakatime used with Sketch?

**Comment by alanhamlett** [comment]
Inside Sketch there is a Plugins -> Manage Plugins menu. Two-finger click on WakaTime and select `Uninstall WakaTime`.

**Comment by alanhamlett** [comment]
Also, each plugin has uninstall instructions on the website:
https://wakatime.com/plugins/sketch/uninstalling
