### ISSUE TITLE
Opening Safari Web Inspector

### ISSUE THREAD

**Issue by RafaelPlantard** [wakatime/sketch-wakatime#5]
When I enable Wakatime plugin always when I start up Sketch is opening a window with Safari Web Inspector.
This just occurs when I enable WakaTime plugin:

<img width="1280" alt="screen shot 2017-04-20 at 21 43 31" src="https://cloud.githubusercontent.com/assets/5968478/25257974/6a4dc4ee-2612-11e7-8363-90d460d1e5ef.png">
<img width="1280" alt="screen shot 2017-04-20 at 21 43 35" src="https://cloud.githubusercontent.com/assets/5968478/25257975/6a82946c-2612-11e7-98af-dcde0b446d2f.png">
<img width="1280" alt="screen shot 2017-04-20 at 21 44 27" src="https://cloud.githubusercontent.com/assets/5968478/25257995/8c126896-2612-11e7-8621-12cb63c3999e.png">

**Comment by meyer** [comment]
@RafaelPlantard I ran into this issue as well with an unrelated plugin. In Safari, take a look at **Develop → [your computer name] → Automatically Show Web Inspector for JSContexts**. Is that checkbox checked?

![screenshot 2017-05-31 17 26 17](https://cloud.githubusercontent.com/assets/13781/26659626/f0b52bec-4626-11e7-9bc2-f24071e1abd5.png)

If you uncheck it, the problem should go away.

**Comment by RafaelPlantard** [comment]
Thanks @meyer it's working. 👍

**Comment by MinhTamCK** [comment]
same me. Thanks meyer.
