### ISSUE TITLE
No time Record

### ISSUE THREAD

**Issue by ChesterYue** [wakatime/sketch-wakatime#8]
Sketch Version：
<img width="396" alt="Screen Shot 2022-01-24 at 10 25 15 AM" src="https://user-images.githubusercontent.com/8273263/150712181-018c21d2-b223-482e-8166-4cbd904d1fae.png">

Sketch Plugin & API Key was set：
<img width="632" alt="Screen Shot 2022-01-24 at 10 25 27 AM" src="https://user-images.githubusercontent.com/8273263/150712206-5f0e50d9-2524-4761-bf05-7b1a2befc950.png">

Plugin Status：
<img width="1256" alt="Screen Shot 2022-01-24 at 10 24 21 AM" src="https://user-images.githubusercontent.com/8273263/150712228-40516910-3d44-4293-ae00-076eb6a68374.png">

**Comment by ChesterYue** [comment]
wakatime-cli installed with brew：
<img width="674" alt="Screen Shot 2022-01-24 at 10 29 28 AM" src="https://user-images.githubusercontent.com/8273263/150712441-7963ea30-2160-40d2-a63c-fb7ef4e273da.png">

**Comment by gandarez** [comment]
Are you behind a proxy? Have you seen any data on dashboard before? Any error or warning on `~/.wakatime.log`?

**Comment by ChesterYue** [comment]
> Are you behind a proxy? Have you seen any data on dashboard before? Any error or warning on `~/.wakatime.log`?

**Are you behind a proxy?**
No. And other IDE work well, VSCode / Vim;

**Have you seen any data on dashboard before:**
Yes. but it was maybe other wakatime-cli version or other sketch plugin version, as you can see here (also wakatime dash board has record):
![Screen Shot 2022-01-24 at 10 52 31 AM](https://user-images.githubusercontent.com/8273263/150714329-41de34e7-28cf-4130-9639-b3c252ceb4ac.png)

**Any error or warning on `~/.wakatime.log`:**
Maybe no. I didn't find any log relative to the sketch plugin. Most was logged by VSCode single file path error.
But, is this used by sketch plugin?:
{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/run.go:240","func":"runCmd","level":"error","message":"failed to run command: sending heartbeat(s) later due to api error: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": EOF","now":"2022-01-23T18:29:47+08:00","version":"v1.35.0"}

**Comment by ChesterYue** [comment]
try reinstall to plugin 2.0, it works (and the cli version shown here is the 10.6.1):

<img width="1111" alt="Screen Shot 2022-01-24 at 10 59 34 AM" src="https://user-images.githubusercontent.com/8273263/150714987-8dd33998-bdfc-4624-9a5a-bbc2bd07464d.png">

<img width="632" alt="Screen Shot 2022-01-24 at 11 00 02 AM" src="https://user-images.githubusercontent.com/8273263/150715024-d5818fc4-ab44-4fa6-be2a-692c00daeb63.png">

**Comment by gandarez** [comment]
Version 2.0 is 3y old and it uses the legacy and outdated python cli. Try running `~/.wakatime/wakatime-cli --offline-count`.

**Comment by ChesterYue** [comment]
> Version 2.0 is 3y old and it uses the legacy and outdated python cli. Try running `~/.wakatime/wakatime-cli --offline-count`.

you mean the cli with ```darwin-amd64``` suffix?
the ```~/.wakatime/wakatime-cli``` with no suffix is a folder.
<img width="1186" alt="Screen Shot 2022-01-24 at 11 21 11 AM" src="https://user-images.githubusercontent.com/8273263/150716828-41941dd7-b7ce-4179-b805-863b3a72070e.png">

**Comment by ChesterYue** [comment]
And i reinstall from 2.0 to 3.0.1 ```~/.wakatime/wakatime-cli-darwin-amd64 --offline-count``` still 0.

**Comment by alanhamlett** [comment]
Can you try deleting your `~/.wakatime/` folder and then restart Sketch? That will re-download wakatime-cli to `~/.wakatime/` since it should be a symlink at `~/.wakatime/wakatime-cli` not a folder.

Every time you restart Sketch, the wakatime plugin runs [this install script](https://github.com/wakatime/sketch-wakatime/blob/984e5a3daf8ef498de611968b568306191497d1a/WakaTime.sketchplugin/Contents/Resources/install_cli.py).

**Comment by ChesterYue** [comment]
> Can you try deleting your `~/.wakatime/` folder and then restart Sketch? That will re-download wakatime-cli to `~/.wakatime/` since it should be a symlink at `~/.wakatime/wakatime-cli` not a folder.
> 
> Every time you restart Sketch, the wakatime plugin runs [this install script](https://github.com/wakatime/sketch-wakatime/blob/984e5a3daf8ef498de611968b568306191497d1a/WakaTime.sketchplugin/Contents/Resources/install_cli.py).

After delete the whole `~/.wakatime/` folder. Restart Sketch with plugin 3.0.1:

1. `~/.wakatime/wakatime-cli` link to `~/.wakatime/wakatime-cli-darwin-amd64`.
2. with the folder is deleted, `~/.wakatime/wakatime-cli-darwin-amd64` is not there.
3. the `wakatime-cli.zip` here seems empty.

<img width="1186" alt="Screen Shot 2022-01-24 at 2 11 34 PM" src="https://user-images.githubusercontent.com/8273263/150731064-30c62478-18e5-4df1-be0d-7e9f5755202a.png">

**Comment by ChesterYue** [comment]
After run the scripts manually, seems download / unzip / link success:

<img width="898" alt="Screen Shot 2022-01-24 at 2 20 41 PM" src="https://user-images.githubusercontent.com/8273263/150732003-9ecee90e-2ec4-410f-8f68-d7bdfa10936d.png">

And, the plugin status shows right:
<img width="1343" alt="Screen Shot 2022-01-24 at 2 21 34 PM" src="https://user-images.githubusercontent.com/8273263/150732158-fd59ad2b-84b3-4af9-ac12-4b3e70455a66.png">

**Comment by ChesterYue** [comment]
I re delete the folder several times then restart Sketch.
It can download / unzip / link success.
Not sure why the first time not working. (Maybe the networking? No?)

**Comment by ChesterYue** [comment]
two question remains:

1. was the folder and link conflict above caused by upgrade from 2.0 to 3.0?
2. what's the difference between `~/.wakatime/wakatime-cli`(link to `~/.wakatime/wakatime-cli-darwin-amd64`) with `/usr/local/bin/wakatime-cli` (installed with home brew)?  different IDE not use the same?

**Comment by alanhamlett** [comment]
Installing wakatime-cli with Homebrew (`/usr/local/bin/wakatime-cli`) is only needed for the Emacs and Terminal plugins. All other WakaTime plugins download wakatime-cli automatically into `~/.wakatime/wakatime-cli-<os>-<arch>` and symlink `~/.wakatime/wakatime-cli` for some plugins (Vim) to make it simpler and faster. Vim needs to fork a process to detect os/arch so it uses the symlink to speed up startup time.

Now that it's working, it must have been from the old version. It used to use `~/.wakatime/wakatime-master/` for the old wakatime-cli but maybe somehow it used `~/.wakatime/wakatime-cli/` which caused the newest plugin to break. Glad you got it working now!
